---
#  Tareas para la instalación de Tomcat
#  v0 Instalación inicial

- name: Creación del grupo de aplicaciones
  become: yes
  become_method: sudo
  group:
    name: "{{ tomcat_group }}"

- name: Creación del usuarios para el servicio
  become: yes
  become_method: sudo
  user:
    name: "{{ tomcat_user }}"
    system: yes
    home: "/import/software/{{ tomcat_user }}"
    shell: /bin/bash
    group: "{{ tomcat_group }}"
    createhome: no
    state: present


- name: Comprobamos si existe una version previamente descargada
  stat:
    path: "/tmp/{{ tomcat_archive }}"
  register: version_descargada

- debug:
  msg: "tomcat-{{ version.split('.')[0] }}"

- name: Descarga tomcat "{{ version }}"
  environment: "{{ proxy_env }}"
  become: yes
  become_method: sudo
  get_url:
    url: "http://archive.apache.org/dist/tomcat/tomcat-{{ version.split('.')[-3] }}/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz"
    dest: "/tmp/{{ tomcat_archive }}"
  when: not version_descargada.stat.exists

- name: Comprobamos si existe el directorio destino ( solo soportamos instalación no update )
  stat:
    path: "{{ catalina_base }}"
  register: version_desplegada

- name: Se crea el directorio destino si no existe
  become: yes
  become_method: sudo
  file:
    path: "{{ catalina_base }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0775
    recurse: yes
  when: not version_desplegada.stat.exists

- name: Extraer en directorio
  become: yes
  become_method: sudo
  unarchive:
    src: "{{ item }}"
    dest: "{{ software_base }}"
    remote_src: True
    mode: 0755
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_items:
    - "/tmp/{{ tomcat_archive }}"
  when: not version_desplegada.stat.exists

- name: Creación o modificación del enlace de tomcat a la instancia desplegada
  become: yes
  become_method: sudo
  file:
    state: link
    src: "{{ catalina_base }}"
    dest: "{{ catalina_home }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
#  when: not version_desplegada.stat.exists

- name: Ponemos el script catalina.sh
  become: yes
  become_method: sudo
  template:
    src: catalina.sh.j2
    dest: "{{ catalina_home }}/bin/catalina.sh"
    mode: '0750'
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  tags:
    - config

- name: Ponemos el server.xml
  become: yes
  become_method: sudo
  template:
    src: server.xml.j2
    dest: "{{ catalina_home }}/conf/server.xml"
    mode: '0600'
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  tags:
    - config

- name: Ponemos el script de arranque en su ubicación si es RH 6.X
  become: yes
  become_method: sudo
  template:
    src: tomcat.init.j2
    dest: "/etc/init.d/{{ tomcat_instance }}"
    mode: '0750'
  notify: restart tomcat
  when: (ansible_distribution_major_version == "6")
  tags:
    - initd
    - config

- name: Ponemos el servicio de  arranque en su ubicación si es RH 7.X
  become: yes
  become_method: sudo
  template:
    src: tomcat.systemd.j2
    dest: "/usr/lib/systemd/system/{{ tomcat_instance }}.service"
    mode: '0644'
  when: (ansible_distribution_major_version == "7")
  tags:
    - systemd
    - config

#- name: Procedemos a recargar el systemd
#  become: true
#  become_method: sudo
#  systemd:
#    name: "{{ tomcat_instance }}.service"
#    enabled: yes
#    state: started
#    masked: no
#  notify: restart tomcat
#  when: (ansible_distribution_major_version == "7")
#  tags:
#   - systemd
