---
- name: #TC7003 Se establece las claves de los roles de accesso mediante JMX
  become: yes
  become_method: sudo
  template:
    src: jmxremote.password.j2
    dest: "{{ catalina_home }}/conf/jmxremote.password"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '600'

