---
# handlers file for cfv.tomcat7
- name: restart tomcat
  become: yes
  become_method: sudo
  service:
    name: "{{ tomcat_instance }}"
    state: restarted

- name: start tomcat
  become: yes
  become_method: sudo
  service:
    name: "{{ tomcat_instance }}"
    state: started
